plugins:
- "@semantic-release/commit-analyzer",
- "@semantic-release/release-notes-generator",
- - "@semantic-release/changelog",
    changelogFile: CHANGELOG.md
- semantic-release-license
- - "@semantic-release/git"
    assets:
    - LICENSE
    - CHANGELOG.md
- "@semantic-release/github"
